### PR TITLE
Upgrade Jedis and Logback version

### PR DESCRIPTION
**Pull request by sergioasantiago**

### CODE REVIEW

**Comment by rlapray** [comment]
Thank you @sergioasantiago ! I was going to code this myself this afternoon but you wrote this 2 weeks ago ! @kmtong FYI I will be using this as soon as it's merged, really looking forward for it :)

**Comment by Sadovnikov94** [comment]
@sergioasantiago does repo dead already?

**Comment by sergioasantiago** [comment]
Yes seems so. There are some open PR from 2 or 3 years ago......

**Comment by kmtong** [comment]
sorry to response late and thanks for the update.

**Comment by derkoe** [comment]
@kmtong would be great to have a release including this fix

**Pull request merged**
